### PR TITLE
Scripts and documentation to prep data and train model

### PR DESCRIPTION
**Pull request by bkowshik**
Per https://github.com/mapbox/osmcha/pull/5#issuecomment-276727180

## Objective
- Scripts and documentation to prep data and train model
- Add useful hyperlinks onto README

### CODE REVIEW

**Comment by rodowi** [comment]
Also, can we rename 'Instructions to prep data and train model' to 'Add scripts and docs for data prep and training'? to make it clear that the commit not only adds docs but also the scripts

**Comment by bkowshik** [comment]
> Also, can we rename 'Instructions to prep data and train model' to 'Add scripts and docs for data prep and training'?

This was wonderful to learn about. `git` is amazing!

## Documentation
- [Amending older or multiple commit messages](https://help.github.com/articles/changing-a-commit-message/#amending-older-or-multiple-commit-messages)

**Comment by bkowshik** [comment]
> LGTM, I fixed the train/test partition in 79d18ff. If that works for you we can merge.

@rodowi, I did the [commit message rename](https://github.com/mapbox/gabbar/pull/3#issuecomment-277812012) first and that resulted in your commit go missing. I have added that back with https://github.com/mapbox/gabbar/pull/3/commits/ce904ace79e471a456979246ac92821dac19453d 😃 

screen shot 2017-02-07 at 3 59 10 pm

**Comment by rodowi** [comment]
> and that resulted in your commit go missing

no worries
good that the code was merged

**Pull request merged**
